services:

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      CONFIG_URL: /app/swagger-config.yaml
    volumes:
      - ./swagger:/usr/share/nginx/html/app # Mapeo correcto de la carpeta swagger a la ruta que Swagger espera
    networks:
      - api-network

  prism-mock:
    image: stoplight/prism:4
    container_name: prism-mock
    command: mock -h 0.0.0.0 /app/api-test.yaml
    ports:
      - "4010:4010"
    volumes:
      - ./swagger:/app
    networks:
      - api-network

networks:
  api-network:
    driver: bridge