services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /app/openapi.yaml
    volumes:
      - ./swagger:/app
    networks:
      - api-network

  prism-mock:
    image: stoplight/prism:4
    container_name: prism-mock
    command: mock -h 0.0.0.0 /app/openapi.yaml
    ports:
      - "4010:4010"
    volumes:
      - ./swagger:/app
      - ./logs:/var/log/prism
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
