openapi: 3.0.0
info:
  title: APIForge2
  version: 1.0.0
  description: API estándar para proyectos generales de desarrollo.

servers:
  - url: http://localhost:4010

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /resources:
    get:
      summary: Obtener lista de recursos
      security:
        - ApiKeyAuth: []
        - BearerAuth: []
      responses:
        '200':
          description: "Lista de recursos"
          content:
            application/json:
              examples:
                example-1:
                  value: [{ "id": 1, "nombre": "Recurso 1", "descripcion": "Descripción del recurso" }]
        '401':
          description: "No autorizado. Token o API Key faltante"
          content:
            application/json:
              examples:
                unauthorized:
                  value:
                    status: "error"
                    message: "Unauthorized"
